FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    make \
    && apt-get clean

WORKDIR /app

COPY . .

RUN mkdir -p build
RUN cd build && cmake .. && make && mv ./ClubManager ../